### ISSUE TITLE
NPE Log Spam

### ISSUE THREAD

**Issue by ghost** [wolforcept/Vaultopic#9] opened 2019-10-23 17:20 UTC
Possibly related to #1.

Constant running:
[10:18:12] [Client thread/INFO] [STDERR]: [wolforce.vaultopic.client.Projector:loadMatrixes:51]: java.lang.NullPointerException

Repeated over and over. I didn't count, but it looks like every tick. Even when SSP paused.

**Comment by TheDeviantCrafter** [comment] 2019-10-26 03:00
Duplicate of #1

**Comment by katubug** [comment] 2019-12-22 03:58
I'd love it if a fix for this was released to CurseForge, so I could include this mod in my modpack. As it stands, opening my latest.log actually crashed Notepad. I am not comfortable having to accept bug reports for my pack if provided logs are going to be prohibitive to access and upload, but I'd really like this mod if possible.

Thanks for your time!

**Closed as completed** 2020-01-11 11:14 UTC
